-- Deuxième lot d'horaires relevés en ligne, les 121 vraies fiches
-- restantes après le pilote de la 0006. Même méthode, même limite :
-- une seule plage ouvre/ferme par jour, aucune prestation ajoutée (ce
-- qui donnerait un bouton de rendez-vous sur une fiche que personne ne
-- surveille), et la fiche affiche déjà l'avertissement "non confirmés
-- par le salon".
--
-- 97 salons retenus sur 121, 24 laissés de côté : pas d'horaires
-- fiables trouvés, coupure méridienne que le schéma ne représente pas,
-- ou sources contradictoires entre agrégateurs. Le détail est dans les
-- commentaires après chaque bloc.
--
-- Cas particulier : coiffure-de-l-amitie-montrouge semble avoir fermé
-- fin 2023 d'après les recherches. Sa fiche existe toujours dans
-- l'annuaire (adresse relevée en août 2026) mais mérite une
-- vérification séparée, indépendante de cette migration.
--
-- Cas particulier bis : french-barber-rueil-rueil-malmaison n'a pas de
-- fiche trouvée sous ce nom exact. Les horaires ci-dessous viennent
-- d'une fiche "Barbershop Rueil" à la même adresse (65 avenue Paul
-- Doumer, 92500 Rueil-Malmaison) — confirmé par Kader, ce sont les
-- bonnes horaires pour ce salon.
--
-- Rejouable comme la 0006 : chaque insert ne vise que les salons réels
-- et non réclamés (s.demo = false et s.gerant_id is null).

insert into public.horaires (salon_id, jour, ouvre, ferme)
select s.id, h.jour, h.ouvre, h.ferme
  from public.salons s
  join (values
    ('beauty-barber-du-forum-boulogne-billancourt', 0::smallint, '11:00'::time, '18:00'::time),
    ('beauty-barber-du-forum-boulogne-billancourt', 1::smallint, '10:00'::time, '20:00'::time),
    ('beauty-barber-du-forum-boulogne-billancourt', 2::smallint, '10:00'::time, '20:00'::time),
    ('beauty-barber-du-forum-boulogne-billancourt', 3::smallint, '10:00'::time, '20:00'::time),
    ('beauty-barber-du-forum-boulogne-billancourt', 4::smallint, '10:00'::time, '20:00'::time),
    ('beauty-barber-du-forum-boulogne-billancourt', 5::smallint, '10:00'::time, '20:00'::time),
    ('beauty-barber-du-forum-boulogne-billancourt', 6::smallint, '10:00'::time, '20:00'::time),
    ('beauty-jess-issy-les-moulineaux', 0::smallint, null, null),
    ('beauty-jess-issy-les-moulineaux', 1::smallint, null, null),
    ('beauty-jess-issy-les-moulineaux', 2::smallint, '10:00'::time, '18:30'::time),
    ('beauty-jess-issy-les-moulineaux', 3::smallint, '10:00'::time, '18:30'::time),
    ('beauty-jess-issy-les-moulineaux', 4::smallint, '10:00'::time, '18:30'::time),
    ('beauty-jess-issy-les-moulineaux', 5::smallint, '10:00'::time, '18:30'::time),
    ('beauty-jess-issy-les-moulineaux', 6::smallint, '09:30'::time, '17:00'::time),
    ('belom-issy-les-moulineaux', 0::smallint, null, null),
    ('belom-issy-les-moulineaux', 1::smallint, null, null),
    ('belom-issy-les-moulineaux', 2::smallint, '09:00'::time, '19:00'::time),
    ('belom-issy-les-moulineaux', 3::smallint, '09:00'::time, '19:00'::time),
    ('belom-issy-les-moulineaux', 4::smallint, '09:00'::time, '19:00'::time),
    ('belom-issy-les-moulineaux', 5::smallint, '09:00'::time, '19:00'::time),
    ('belom-issy-les-moulineaux', 6::smallint, '09:00'::time, '19:00'::time),
    ('ben-s-barber-levallois-perret', 0::smallint, '11:00'::time, '19:00'::time),
    ('ben-s-barber-levallois-perret', 1::smallint, '10:00'::time, '20:00'::time),
    ('ben-s-barber-levallois-perret', 2::smallint, '10:00'::time, '20:00'::time),
    ('ben-s-barber-levallois-perret', 3::smallint, '10:00'::time, '20:00'::time),
    ('ben-s-barber-levallois-perret', 4::smallint, '10:00'::time, '20:00'::time),
    ('ben-s-barber-levallois-perret', 5::smallint, '10:00'::time, '20:00'::time),
    ('ben-s-barber-levallois-perret', 6::smallint, '10:00'::time, '20:00'::time),
    ('blackbox-boulogne-billancourt', 0::smallint, '10:00'::time, '21:00'::time),
    ('blackbox-boulogne-billancourt', 1::smallint, '10:00'::time, '21:00'::time),
    ('blackbox-boulogne-billancourt', 2::smallint, '10:00'::time, '21:00'::time),
    ('blackbox-boulogne-billancourt', 3::smallint, '10:00'::time, '21:00'::time),
    ('blackbox-boulogne-billancourt', 4::smallint, '10:00'::time, '21:00'::time),
    ('blackbox-boulogne-billancourt', 5::smallint, '10:00'::time, '21:00'::time),
    ('blackbox-boulogne-billancourt', 6::smallint, '10:00'::time, '21:00'::time),
    ('bros-barber-boulogne-billancourt', 0::smallint, '10:00'::time, '19:00'::time),
    ('bros-barber-boulogne-billancourt', 1::smallint, null, null),
    ('bros-barber-boulogne-billancourt', 2::smallint, '10:00'::time, '19:00'::time),
    ('bros-barber-boulogne-billancourt', 3::smallint, '10:00'::time, '19:00'::time),
    ('bros-barber-boulogne-billancourt', 4::smallint, '10:00'::time, '19:00'::time),
    ('bros-barber-boulogne-billancourt', 5::smallint, '10:00'::time, '19:00'::time),
    ('bros-barber-boulogne-billancourt', 6::smallint, '10:00'::time, '19:00'::time),
    ('chez-nico-chatillon', 0::smallint, null, null),
    ('chez-nico-chatillon', 1::smallint, '10:30'::time, '19:00'::time),
    ('chez-nico-chatillon', 2::smallint, '10:30'::time, '19:00'::time),
    ('chez-nico-chatillon', 3::smallint, '10:30'::time, '19:00'::time),
    ('chez-nico-chatillon', 4::smallint, '10:30'::time, '19:00'::time),
    ('chez-nico-chatillon', 5::smallint, '10:30'::time, '19:00'::time),
    ('chez-nico-chatillon', 6::smallint, '10:30'::time, '18:00'::time),
    ('coiffeur-barbier-skyby-rubio-issy-les-moulineaux', 0::smallint, null, null),
    ('coiffeur-barbier-skyby-rubio-issy-les-moulineaux', 1::smallint, '12:00'::time, '20:00'::time),
    ('coiffeur-barbier-skyby-rubio-issy-les-moulineaux', 2::smallint, '10:00'::time, '20:00'::time),
    ('coiffeur-barbier-skyby-rubio-issy-les-moulineaux', 3::smallint, '10:00'::time, '20:00'::time),
    ('coiffeur-barbier-skyby-rubio-issy-les-moulineaux', 4::smallint, '10:00'::time, '20:00'::time),
    ('coiffeur-barbier-skyby-rubio-issy-les-moulineaux', 5::smallint, '10:00'::time, '20:00'::time),
    ('coiffeur-barbier-skyby-rubio-issy-les-moulineaux', 6::smallint, '09:00'::time, '19:00'::time),
    ('costi-coiffure-boulogne-billancourt', 0::smallint, null, null),
    ('costi-coiffure-boulogne-billancourt', 1::smallint, '09:30'::time, '19:00'::time),
    ('costi-coiffure-boulogne-billancourt', 2::smallint, '09:30'::time, '19:00'::time),
    ('costi-coiffure-boulogne-billancourt', 3::smallint, '09:30'::time, '19:00'::time),
    ('costi-coiffure-boulogne-billancourt', 4::smallint, '09:30'::time, '19:00'::time),
    ('costi-coiffure-boulogne-billancourt', 5::smallint, '09:30'::time, '19:00'::time),
    ('costi-coiffure-boulogne-billancourt', 6::smallint, '09:00'::time, '19:00'::time),
    ('dukes-barber-sceaux', 0::smallint, null, null),
    ('dukes-barber-sceaux', 1::smallint, '10:00'::time, '19:00'::time),
    ('dukes-barber-sceaux', 2::smallint, '10:00'::time, '19:00'::time),
    ('dukes-barber-sceaux', 3::smallint, '10:00'::time, '19:00'::time),
    ('dukes-barber-sceaux', 4::smallint, '10:00'::time, '19:00'::time),
    ('dukes-barber-sceaux', 5::smallint, '10:00'::time, '19:00'::time),
    ('dukes-barber-sceaux', 6::smallint, '10:00'::time, '19:00'::time),
    ('french-barber-courbevoie-courbevoie', 0::smallint, null, null),
    ('french-barber-courbevoie-courbevoie', 1::smallint, '10:00'::time, '20:00'::time),
    ('french-barber-courbevoie-courbevoie', 2::smallint, '10:00'::time, '20:00'::time),
    ('french-barber-courbevoie-courbevoie', 3::smallint, '10:00'::time, '20:00'::time),
    ('french-barber-courbevoie-courbevoie', 4::smallint, '10:00'::time, '20:00'::time),
    ('french-barber-courbevoie-courbevoie', 5::smallint, '10:00'::time, '20:00'::time),
    ('french-barber-courbevoie-courbevoie', 6::smallint, '10:00'::time, '20:00'::time),
    ('french-barber-la-garenne-colombes-la-garenne-colombes', 0::smallint, '10:00'::time, '19:30'::time),
    ('french-barber-la-garenne-colombes-la-garenne-colombes', 1::smallint, '10:00'::time, '19:30'::time),
    ('french-barber-la-garenne-colombes-la-garenne-colombes', 2::smallint, '10:00'::time, '19:30'::time),
    ('french-barber-la-garenne-colombes-la-garenne-colombes', 3::smallint, '10:00'::time, '19:30'::time),
    ('french-barber-la-garenne-colombes-la-garenne-colombes', 4::smallint, '10:00'::time, '19:30'::time),
    ('french-barber-la-garenne-colombes-la-garenne-colombes', 5::smallint, '10:00'::time, '19:30'::time),
    ('french-barber-la-garenne-colombes-la-garenne-colombes', 6::smallint, '10:00'::time, '19:30'::time),
    ('french-barber-rueil-rueil-malmaison', 0::smallint, '09:30'::time, '19:00'::time),
    ('french-barber-rueil-rueil-malmaison', 1::smallint, null, null),
    ('french-barber-rueil-rueil-malmaison', 2::smallint, '09:30'::time, '19:30'::time),
    ('french-barber-rueil-rueil-malmaison', 3::smallint, '09:30'::time, '19:30'::time),
    ('french-barber-rueil-rueil-malmaison', 4::smallint, '09:30'::time, '19:30'::time),
    ('french-barber-rueil-rueil-malmaison', 5::smallint, '09:30'::time, '19:30'::time),
    ('french-barber-rueil-rueil-malmaison', 6::smallint, '09:30'::time, '19:30'::time),
    ('the-nine-barbershop-rueil-malmaison', 0::smallint, null, null),
    ('the-nine-barbershop-rueil-malmaison', 1::smallint, null, null),
    ('the-nine-barbershop-rueil-malmaison', 2::smallint, '10:00'::time, '20:00'::time),
    ('the-nine-barbershop-rueil-malmaison', 3::smallint, '10:00'::time, '20:00'::time),
    ('the-nine-barbershop-rueil-malmaison', 4::smallint, '10:00'::time, '20:00'::time),
    ('the-nine-barbershop-rueil-malmaison', 5::smallint, '10:00'::time, '21:00'::time),
    ('the-nine-barbershop-rueil-malmaison', 6::smallint, '10:00'::time, '21:00'::time),
    ('golden-scissors-issy-les-moulineaux', 0::smallint, '10:00'::time, '20:00'::time),
    ('golden-scissors-issy-les-moulineaux', 1::smallint, '10:00'::time, '20:00'::time),
    ('golden-scissors-issy-les-moulineaux', 2::smallint, '10:00'::time, '20:00'::time),
    ('golden-scissors-issy-les-moulineaux', 3::smallint, '10:00'::time, '20:00'::time),
    ('golden-scissors-issy-les-moulineaux', 4::smallint, '10:00'::time, '20:00'::time),
    ('golden-scissors-issy-les-moulineaux', 5::smallint, '10:00'::time, '20:00'::time),
    ('golden-scissors-issy-les-moulineaux', 6::smallint, '10:00'::time, '20:00'::time),
    ('hair-spur-antony', 0::smallint, null, null),
    ('hair-spur-antony', 1::smallint, null, null),
    ('hair-spur-antony', 2::smallint, '09:00'::time, '19:00'::time),
    ('hair-spur-antony', 3::smallint, '09:00'::time, '19:00'::time),
    ('hair-spur-antony', 4::smallint, '09:00'::time, '19:00'::time),
    ('hair-spur-antony', 5::smallint, '09:00'::time, '19:00'::time),
    ('hair-spur-antony', 6::smallint, '09:00'::time, '19:00'::time),
    ('hairbyshe-nanterre', 0::smallint, null, null),
    ('hairbyshe-nanterre', 1::smallint, '10:00'::time, '20:00'::time),
    ('hairbyshe-nanterre', 2::smallint, '10:00'::time, '20:00'::time),
    ('hairbyshe-nanterre', 3::smallint, '10:00'::time, '20:00'::time),
    ('hairbyshe-nanterre', 4::smallint, '10:00'::time, '20:00'::time),
    ('hairbyshe-nanterre', 5::smallint, '10:00'::time, '20:00'::time),
    ('hairbyshe-nanterre', 6::smallint, '10:00'::time, '20:00'::time),
    ('jackson-911-rueil-malmaison', 0::smallint, '12:00'::time, '20:00'::time),
    ('jackson-911-rueil-malmaison', 1::smallint, '10:00'::time, '20:00'::time),
    ('jackson-911-rueil-malmaison', 2::smallint, '10:00'::time, '20:00'::time),
    ('jackson-911-rueil-malmaison', 3::smallint, '10:00'::time, '20:00'::time),
    ('jackson-911-rueil-malmaison', 4::smallint, '10:00'::time, '20:00'::time),
    ('jackson-911-rueil-malmaison', 5::smallint, '10:00'::time, '20:00'::time),
    ('jackson-911-rueil-malmaison', 6::smallint, '10:00'::time, '20:00'::time),
    ('katia-g-coiffure-levallois-perret', 0::smallint, null, null),
    ('katia-g-coiffure-levallois-perret', 1::smallint, null, null),
    ('katia-g-coiffure-levallois-perret', 2::smallint, '09:30'::time, '19:00'::time),
    ('katia-g-coiffure-levallois-perret', 3::smallint, '09:30'::time, '19:00'::time),
    ('katia-g-coiffure-levallois-perret', 4::smallint, '09:30'::time, '19:00'::time),
    ('katia-g-coiffure-levallois-perret', 5::smallint, '09:30'::time, '19:00'::time),
    ('katia-g-coiffure-levallois-perret', 6::smallint, '09:00'::time, '18:00'::time),
    ('kome-prestige-rueil-malmaison', 0::smallint, null, null),
    ('kome-prestige-rueil-malmaison', 1::smallint, '09:30'::time, '19:00'::time),
    ('kome-prestige-rueil-malmaison', 2::smallint, '09:00'::time, '19:00'::time),
    ('kome-prestige-rueil-malmaison', 3::smallint, '09:00'::time, '19:00'::time),
    ('kome-prestige-rueil-malmaison', 4::smallint, '09:00'::time, '19:00'::time),
    ('kome-prestige-rueil-malmaison', 5::smallint, '09:00'::time, '19:30'::time),
    ('kome-prestige-rueil-malmaison', 6::smallint, '09:00'::time, '19:00'::time),
    ('le-barbier-club-saint-cloud', 0::smallint, null, null),
    ('le-barbier-club-saint-cloud', 1::smallint, '09:30'::time, '19:30'::time),
    ('le-barbier-club-saint-cloud', 2::smallint, null, null),
    ('le-barbier-club-saint-cloud', 3::smallint, '09:30'::time, '19:30'::time),
    ('le-barbier-club-saint-cloud', 4::smallint, '09:30'::time, '19:30'::time),
    ('le-barbier-club-saint-cloud', 5::smallint, '09:30'::time, '19:30'::time),
    ('le-barbier-club-saint-cloud', 6::smallint, '09:30'::time, '19:30'::time),
    ('le-beau-cercle-issy-les-moulineaux', 0::smallint, '10:00'::time, '20:30'::time),
    ('le-beau-cercle-issy-les-moulineaux', 1::smallint, '10:00'::time, '20:30'::time),
    ('le-beau-cercle-issy-les-moulineaux', 2::smallint, '10:00'::time, '20:30'::time),
    ('le-beau-cercle-issy-les-moulineaux', 3::smallint, '10:00'::time, '20:30'::time),
    ('le-beau-cercle-issy-les-moulineaux', 4::smallint, '10:00'::time, '20:30'::time),
    ('le-beau-cercle-issy-les-moulineaux', 5::smallint, '10:00'::time, '20:30'::time),
    ('le-beau-cercle-issy-les-moulineaux', 6::smallint, '10:00'::time, '20:30'::time)
  ) as h(slug, jour, ouvre, ferme)
    on h.slug = s.slug
 where s.demo = false
   and s.gerant_id is null
on conflict (salon_id, jour) do update
  set ouvre = excluded.ouvre,
      ferme = excluded.ferme;

-- Ignorés (lot 1/5) :
-- charles-b-barbers-groomers-levallois-perret : coupure déjeuner (mar-sam 10:00-13:20 puis 14:20-19:00)
-- la-parisienne-beauty-nanterre : sources contradictoires (Fresha et Planity ne s'accordent ni sur les jours ni sur les heures)

insert into public.horaires (salon_id, jour, ouvre, ferme)
select s.id, h.jour, h.ouvre, h.ferme
  from public.salons s
  join (values
    ('les-barboristes-boulogne-boulogne-billancourt', 0::smallint, null, null),
    ('les-barboristes-boulogne-boulogne-billancourt', 1::smallint, null, null),
    ('les-barboristes-boulogne-boulogne-billancourt', 2::smallint, '10:20'::time, '20:00'::time),
    ('les-barboristes-boulogne-boulogne-billancourt', 3::smallint, '10:20'::time, '20:00'::time),
    ('les-barboristes-boulogne-boulogne-billancourt', 4::smallint, '10:20'::time, '20:00'::time),
    ('les-barboristes-boulogne-boulogne-billancourt', 5::smallint, '10:20'::time, '20:00'::time),
    ('les-barboristes-boulogne-boulogne-billancourt', 6::smallint, '09:00'::time, '19:00'::time),
    ('les-barboristes-rueil-rueil-malmaison', 0::smallint, null, null),
    ('les-barboristes-rueil-rueil-malmaison', 1::smallint, null, null),
    ('les-barboristes-rueil-rueil-malmaison', 2::smallint, '10:20'::time, '20:00'::time),
    ('les-barboristes-rueil-rueil-malmaison', 3::smallint, '10:20'::time, '20:00'::time),
    ('les-barboristes-rueil-rueil-malmaison', 4::smallint, '10:20'::time, '20:00'::time),
    ('les-barboristes-rueil-rueil-malmaison', 5::smallint, '10:20'::time, '20:00'::time),
    ('les-barboristes-rueil-rueil-malmaison', 6::smallint, '09:00'::time, '19:00'::time),
    ('mister-barber-nanterre', 0::smallint, '09:00'::time, '20:00'::time),
    ('mister-barber-nanterre', 1::smallint, '09:00'::time, '20:00'::time),
    ('mister-barber-nanterre', 2::smallint, '09:00'::time, '20:00'::time),
    ('mister-barber-nanterre', 3::smallint, '09:00'::time, '20:00'::time),
    ('mister-barber-nanterre', 4::smallint, '09:00'::time, '20:00'::time),
    ('mister-barber-nanterre', 5::smallint, '09:00'::time, '20:00'::time),
    ('mister-barber-nanterre', 6::smallint, '09:00'::time, '20:00'::time),
    ('r-barber-neuilly-sur-seine', 0::smallint, null, null),
    ('r-barber-neuilly-sur-seine', 1::smallint, '10:00'::time, '20:00'::time),
    ('r-barber-neuilly-sur-seine', 2::smallint, '10:00'::time, '20:00'::time),
    ('r-barber-neuilly-sur-seine', 3::smallint, '10:00'::time, '20:00'::time),
    ('r-barber-neuilly-sur-seine', 4::smallint, '10:00'::time, '20:00'::time),
    ('r-barber-neuilly-sur-seine', 5::smallint, '10:00'::time, '20:00'::time),
    ('r-barber-neuilly-sur-seine', 6::smallint, '09:30'::time, '20:00'::time),
    ('salongreg-boulogne-billancourt', 0::smallint, null, null),
    ('salongreg-boulogne-billancourt', 1::smallint, null, null),
    ('salongreg-boulogne-billancourt', 2::smallint, '09:00'::time, '19:30'::time),
    ('salongreg-boulogne-billancourt', 3::smallint, '09:00'::time, '19:30'::time),
    ('salongreg-boulogne-billancourt', 4::smallint, '09:00'::time, '19:30'::time),
    ('salongreg-boulogne-billancourt', 5::smallint, '09:00'::time, '19:30'::time),
    ('salongreg-boulogne-billancourt', 6::smallint, '09:00'::time, '19:00'::time),
    ('studio-capillaire-suresnes', 0::smallint, '11:00'::time, '18:00'::time),
    ('studio-capillaire-suresnes', 1::smallint, '12:00'::time, '19:00'::time),
    ('studio-capillaire-suresnes', 2::smallint, null, null),
    ('studio-capillaire-suresnes', 3::smallint, null, null),
    ('studio-capillaire-suresnes', 4::smallint, '11:00'::time, '18:00'::time),
    ('studio-capillaire-suresnes', 5::smallint, '11:00'::time, '18:00'::time),
    ('studio-capillaire-suresnes', 6::smallint, '11:00'::time, '18:00'::time),
    ('tag-barber-shop-neuilly-sur-seine', 0::smallint, null, null),
    ('tag-barber-shop-neuilly-sur-seine', 1::smallint, '10:00'::time, '20:00'::time),
    ('tag-barber-shop-neuilly-sur-seine', 2::smallint, '10:00'::time, '20:00'::time),
    ('tag-barber-shop-neuilly-sur-seine', 3::smallint, '10:00'::time, '20:00'::time),
    ('tag-barber-shop-neuilly-sur-seine', 4::smallint, '10:00'::time, '20:00'::time),
    ('tag-barber-shop-neuilly-sur-seine', 5::smallint, '10:00'::time, '20:00'::time),
    ('tag-barber-shop-neuilly-sur-seine', 6::smallint, '09:00'::time, '18:00'::time),
    ('the-barber-by-lacrim-nanterre', 0::smallint, '10:00'::time, '20:00'::time),
    ('the-barber-by-lacrim-nanterre', 1::smallint, '10:00'::time, '20:00'::time),
    ('the-barber-by-lacrim-nanterre', 2::smallint, '10:00'::time, '20:00'::time),
    ('the-barber-by-lacrim-nanterre', 3::smallint, '10:00'::time, '20:00'::time),
    ('the-barber-by-lacrim-nanterre', 4::smallint, '10:00'::time, '20:00'::time),
    ('the-barber-by-lacrim-nanterre', 5::smallint, '10:00'::time, '20:00'::time),
    ('the-barber-by-lacrim-nanterre', 6::smallint, '10:00'::time, '20:00'::time),
    ('the-barber-company-issy-issy-les-moulineaux', 0::smallint, null, null),
    ('the-barber-company-issy-issy-les-moulineaux', 1::smallint, '10:00'::time, '19:00'::time),
    ('the-barber-company-issy-issy-les-moulineaux', 2::smallint, '10:00'::time, '19:00'::time),
    ('the-barber-company-issy-issy-les-moulineaux', 3::smallint, '10:00'::time, '19:00'::time),
    ('the-barber-company-issy-issy-les-moulineaux', 4::smallint, '10:00'::time, '19:00'::time),
    ('the-barber-company-issy-issy-les-moulineaux', 5::smallint, '10:00'::time, '19:00'::time),
    ('the-barber-company-issy-issy-les-moulineaux', 6::smallint, '10:00'::time, '19:00'::time),
    ('the-barber-company-rueil-rueil-malmaison', 0::smallint, null, null),
    ('the-barber-company-rueil-rueil-malmaison', 1::smallint, '09:00'::time, '19:00'::time),
    ('the-barber-company-rueil-rueil-malmaison', 2::smallint, '09:00'::time, '19:00'::time),
    ('the-barber-company-rueil-rueil-malmaison', 3::smallint, '09:00'::time, '19:00'::time),
    ('the-barber-company-rueil-rueil-malmaison', 4::smallint, '09:00'::time, '19:00'::time),
    ('the-barber-company-rueil-rueil-malmaison', 5::smallint, '09:00'::time, '20:00'::time),
    ('the-barber-company-rueil-rueil-malmaison', 6::smallint, '09:00'::time, '19:00'::time),
    ('the-kut-barber-and-shop-rueil-malmaison', 0::smallint, '10:00'::time, '19:00'::time),
    ('the-kut-barber-and-shop-rueil-malmaison', 1::smallint, null, null),
    ('the-kut-barber-and-shop-rueil-malmaison', 2::smallint, '10:00'::time, '19:00'::time),
    ('the-kut-barber-and-shop-rueil-malmaison', 3::smallint, '10:00'::time, '19:00'::time),
    ('the-kut-barber-and-shop-rueil-malmaison', 4::smallint, '10:00'::time, '19:00'::time),
    ('the-kut-barber-and-shop-rueil-malmaison', 5::smallint, '10:00'::time, '19:00'::time),
    ('the-kut-barber-and-shop-rueil-malmaison', 6::smallint, '10:00'::time, '19:00'::time),
    ('your-barber-92-bagneux', 0::smallint, '10:30'::time, '20:00'::time),
    ('your-barber-92-bagneux', 1::smallint, '10:00'::time, '20:00'::time),
    ('your-barber-92-bagneux', 2::smallint, '10:00'::time, '20:00'::time),
    ('your-barber-92-bagneux', 3::smallint, '10:00'::time, '20:00'::time),
    ('your-barber-92-bagneux', 4::smallint, '10:00'::time, '20:00'::time),
    ('your-barber-92-bagneux', 5::smallint, '10:00'::time, '20:00'::time),
    ('your-barber-92-bagneux', 6::smallint, '10:00'::time, '18:00'::time),
    ('3m-barber-coiffure-antony', 0::smallint, null, null),
    ('3m-barber-coiffure-antony', 1::smallint, '12:00'::time, '20:00'::time),
    ('3m-barber-coiffure-antony', 2::smallint, '10:00'::time, '19:30'::time),
    ('3m-barber-coiffure-antony', 3::smallint, '10:00'::time, '19:30'::time),
    ('3m-barber-coiffure-antony', 4::smallint, '10:00'::time, '19:30'::time),
    ('3m-barber-coiffure-antony', 5::smallint, '10:00'::time, '19:30'::time),
    ('3m-barber-coiffure-antony', 6::smallint, '09:00'::time, '19:00'::time),
    ('jean-claude-biguine-antony', 0::smallint, null, null),
    ('jean-claude-biguine-antony', 1::smallint, '09:30'::time, '19:30'::time),
    ('jean-claude-biguine-antony', 2::smallint, '09:30'::time, '19:30'::time),
    ('jean-claude-biguine-antony', 3::smallint, '09:30'::time, '19:30'::time),
    ('jean-claude-biguine-antony', 4::smallint, '09:30'::time, '19:30'::time),
    ('jean-claude-biguine-antony', 5::smallint, '09:30'::time, '19:30'::time),
    ('jean-claude-biguine-antony', 6::smallint, '09:30'::time, '19:00'::time),
    ('franck-provost-antony-antony', 0::smallint, null, null),
    ('franck-provost-antony-antony', 1::smallint, '10:00'::time, '19:30'::time),
    ('franck-provost-antony-antony', 2::smallint, '09:30'::time, '19:30'::time),
    ('franck-provost-antony-antony', 3::smallint, '09:30'::time, '19:30'::time),
    ('franck-provost-antony-antony', 4::smallint, '09:30'::time, '19:30'::time),
    ('franck-provost-antony-antony', 5::smallint, '09:30'::time, '19:30'::time),
    ('franck-provost-antony-antony', 6::smallint, '09:00'::time, '19:00'::time),
    ('jean-louis-david-antony-antony', 0::smallint, null, null),
    ('jean-louis-david-antony-antony', 1::smallint, null, null),
    ('jean-louis-david-antony-antony', 2::smallint, '09:30'::time, '19:00'::time),
    ('jean-louis-david-antony-antony', 3::smallint, '09:30'::time, '19:00'::time),
    ('jean-louis-david-antony-antony', 4::smallint, '09:30'::time, '19:00'::time),
    ('jean-louis-david-antony-antony', 5::smallint, '09:30'::time, '19:00'::time),
    ('jean-louis-david-antony-antony', 6::smallint, '09:00'::time, '19:00'::time),
    ('pascal-coste-antony-antony', 0::smallint, null, null),
    ('pascal-coste-antony-antony', 1::smallint, null, null),
    ('pascal-coste-antony-antony', 2::smallint, '10:00'::time, '19:00'::time),
    ('pascal-coste-antony-antony', 3::smallint, '10:00'::time, '19:00'::time),
    ('pascal-coste-antony-antony', 4::smallint, '10:00'::time, '19:00'::time),
    ('pascal-coste-antony-antony', 5::smallint, '10:00'::time, '19:00'::time),
    ('pascal-coste-antony-antony', 6::smallint, '10:00'::time, '19:00'::time),
    ('salon-yannick-guillaume-antony', 0::smallint, null, null),
    ('salon-yannick-guillaume-antony', 1::smallint, null, null),
    ('salon-yannick-guillaume-antony', 2::smallint, '09:00'::time, '19:00'::time),
    ('salon-yannick-guillaume-antony', 3::smallint, '09:00'::time, '19:00'::time),
    ('salon-yannick-guillaume-antony', 4::smallint, '09:00'::time, '19:00'::time),
    ('salon-yannick-guillaume-antony', 5::smallint, '09:00'::time, '19:00'::time),
    ('salon-yannick-guillaume-antony', 6::smallint, '09:00'::time, '18:00'::time),
    ('the-best-concept-antony', 0::smallint, null, null),
    ('the-best-concept-antony', 1::smallint, null, null),
    ('the-best-concept-antony', 2::smallint, '09:30'::time, '19:00'::time),
    ('the-best-concept-antony', 3::smallint, '09:30'::time, '19:00'::time),
    ('the-best-concept-antony', 4::smallint, '09:30'::time, '19:00'::time),
    ('the-best-concept-antony', 5::smallint, '09:30'::time, '19:00'::time),
    ('the-best-concept-antony', 6::smallint, '09:00'::time, '19:00'::time),
    ('camille-albane-boulogne-boulogne-billancourt', 0::smallint, null, null),
    ('camille-albane-boulogne-boulogne-billancourt', 1::smallint, '09:30'::time, '18:30'::time),
    ('camille-albane-boulogne-boulogne-billancourt', 2::smallint, '09:00'::time, '19:00'::time),
    ('camille-albane-boulogne-boulogne-billancourt', 3::smallint, '09:00'::time, '19:00'::time),
    ('camille-albane-boulogne-boulogne-billancourt', 4::smallint, '09:00'::time, '19:00'::time),
    ('camille-albane-boulogne-boulogne-billancourt', 5::smallint, '09:00'::time, '19:00'::time),
    ('camille-albane-boulogne-boulogne-billancourt', 6::smallint, '09:00'::time, '19:00'::time),
    ('dessange-boulogne-boulogne-billancourt', 0::smallint, null, null),
    ('dessange-boulogne-boulogne-billancourt', 1::smallint, '09:00'::time, '18:00'::time),
    ('dessange-boulogne-boulogne-billancourt', 2::smallint, '09:00'::time, '19:00'::time),
    ('dessange-boulogne-boulogne-billancourt', 3::smallint, '09:00'::time, '19:00'::time),
    ('dessange-boulogne-boulogne-billancourt', 4::smallint, '09:00'::time, '20:30'::time),
    ('dessange-boulogne-boulogne-billancourt', 5::smallint, '09:00'::time, '19:00'::time),
    ('dessange-boulogne-boulogne-billancourt', 6::smallint, '09:00'::time, '19:00'::time)
  ) as h(slug, jour, ouvre, ferme)
    on h.slug = s.slug
 where s.demo = false
   and s.gerant_id is null
on conflict (salon_id, jour) do update
  set ouvre = excluded.ouvre,
      ferme = excluded.ferme;

-- Ignorés (lot 2/5) :
-- mina-maison-beaute-puteaux : pas d'horaires trouvés (coiffure à domicile)
-- brigitte-coiffure-antony : pas d'horaires trouvés
-- frederic-moreno-antony : pas d'horaires trouvés

insert into public.horaires (salon_id, jour, ouvre, ferme)
select s.id, h.jour, h.ouvre, h.ferme
  from public.salons s
  join (values
    ('franck-provost-boulogne-boulogne-billancourt', 0::smallint, null, null),
    ('franck-provost-boulogne-boulogne-billancourt', 1::smallint, null, null),
    ('franck-provost-boulogne-boulogne-billancourt', 2::smallint, '09:30'::time, '19:30'::time),
    ('franck-provost-boulogne-boulogne-billancourt', 3::smallint, '09:30'::time, '19:30'::time),
    ('franck-provost-boulogne-boulogne-billancourt', 4::smallint, '09:30'::time, '20:00'::time),
    ('franck-provost-boulogne-boulogne-billancourt', 5::smallint, '09:30'::time, '19:30'::time),
    ('franck-provost-boulogne-boulogne-billancourt', 6::smallint, '09:30'::time, '18:30'::time),
    ('gerard-valentino-boulogne-billancourt', 0::smallint, null, null),
    ('gerard-valentino-boulogne-billancourt', 1::smallint, null, null),
    ('gerard-valentino-boulogne-billancourt', 2::smallint, '10:00'::time, '19:00'::time),
    ('gerard-valentino-boulogne-billancourt', 3::smallint, '10:00'::time, '19:00'::time),
    ('gerard-valentino-boulogne-billancourt', 4::smallint, '11:00'::time, '20:00'::time),
    ('gerard-valentino-boulogne-billancourt', 5::smallint, '10:00'::time, '19:00'::time),
    ('gerard-valentino-boulogne-billancourt', 6::smallint, '10:00'::time, '19:00'::time),
    ('h-a-coiffure-boulogne-billancourt', 0::smallint, null, null),
    ('h-a-coiffure-boulogne-billancourt', 1::smallint, null, null),
    ('h-a-coiffure-boulogne-billancourt', 2::smallint, '10:00'::time, '19:00'::time),
    ('h-a-coiffure-boulogne-billancourt', 3::smallint, '10:00'::time, '19:00'::time),
    ('h-a-coiffure-boulogne-billancourt', 4::smallint, '10:00'::time, '19:00'::time),
    ('h-a-coiffure-boulogne-billancourt', 5::smallint, '10:00'::time, '19:00'::time),
    ('h-a-coiffure-boulogne-billancourt', 6::smallint, '10:00'::time, '19:00'::time),
    ('poptif-nanterre', 0::smallint, null, null),
    ('poptif-nanterre', 1::smallint, null, null),
    ('poptif-nanterre', 2::smallint, '09:00'::time, '19:00'::time),
    ('poptif-nanterre', 3::smallint, '09:00'::time, '19:00'::time),
    ('poptif-nanterre', 4::smallint, '09:00'::time, '21:00'::time),
    ('poptif-nanterre', 5::smallint, '09:00'::time, '19:00'::time),
    ('poptif-nanterre', 6::smallint, '07:30'::time, '13:00'::time),
    ('jean-louis-david-boulogne-boulogne-billancourt', 0::smallint, null, null),
    ('jean-louis-david-boulogne-boulogne-billancourt', 1::smallint, '10:00'::time, '20:00'::time),
    ('jean-louis-david-boulogne-boulogne-billancourt', 2::smallint, '10:00'::time, '20:00'::time),
    ('jean-louis-david-boulogne-boulogne-billancourt', 3::smallint, '10:00'::time, '20:00'::time),
    ('jean-louis-david-boulogne-boulogne-billancourt', 4::smallint, '10:00'::time, '20:00'::time),
    ('jean-louis-david-boulogne-boulogne-billancourt', 5::smallint, '10:00'::time, '20:00'::time),
    ('jean-louis-david-boulogne-boulogne-billancourt', 6::smallint, '10:00'::time, '20:00'::time),
    ('johann-bartoche-boulogne-billancourt', 0::smallint, null, null),
    ('johann-bartoche-boulogne-billancourt', 1::smallint, '10:00'::time, '21:00'::time),
    ('johann-bartoche-boulogne-billancourt', 2::smallint, '10:00'::time, '21:00'::time),
    ('johann-bartoche-boulogne-billancourt', 3::smallint, '11:00'::time, '21:00'::time),
    ('johann-bartoche-boulogne-billancourt', 4::smallint, '10:00'::time, '21:00'::time),
    ('johann-bartoche-boulogne-billancourt', 5::smallint, '10:00'::time, '21:00'::time),
    ('johann-bartoche-boulogne-billancourt', 6::smallint, '09:00'::time, '20:00'::time),
    ('blackbox-levallois-levallois-perret', 0::smallint, '11:00'::time, '22:00'::time),
    ('blackbox-levallois-levallois-perret', 1::smallint, '11:00'::time, '22:00'::time),
    ('blackbox-levallois-levallois-perret', 2::smallint, '11:00'::time, '22:00'::time),
    ('blackbox-levallois-levallois-perret', 3::smallint, '11:00'::time, '22:00'::time),
    ('blackbox-levallois-levallois-perret', 4::smallint, '11:00'::time, '22:00'::time),
    ('blackbox-levallois-levallois-perret', 5::smallint, '11:00'::time, '22:00'::time),
    ('blackbox-levallois-levallois-perret', 6::smallint, '11:00'::time, '22:00'::time),
    ('dessange-levallois-levallois-perret', 0::smallint, null, null),
    ('dessange-levallois-levallois-perret', 1::smallint, null, null),
    ('dessange-levallois-levallois-perret', 2::smallint, '09:00'::time, '18:30'::time),
    ('dessange-levallois-levallois-perret', 3::smallint, '09:00'::time, '18:30'::time),
    ('dessange-levallois-levallois-perret', 4::smallint, '09:00'::time, '18:30'::time),
    ('dessange-levallois-levallois-perret', 5::smallint, '09:00'::time, '18:30'::time),
    ('dessange-levallois-levallois-perret', 6::smallint, '09:00'::time, '18:30'::time),
    ('le-salon-levallois-perret', 0::smallint, null, null),
    ('le-salon-levallois-perret', 1::smallint, null, null),
    ('le-salon-levallois-perret', 2::smallint, '10:00'::time, '19:00'::time),
    ('le-salon-levallois-perret', 3::smallint, '10:00'::time, '19:00'::time),
    ('le-salon-levallois-perret', 4::smallint, '10:00'::time, '19:00'::time),
    ('le-salon-levallois-perret', 5::smallint, '10:00'::time, '19:00'::time),
    ('le-salon-levallois-perret', 6::smallint, '09:30'::time, '18:30'::time),
    ('saint-algue-levallois-levallois-perret', 0::smallint, null, null),
    ('saint-algue-levallois-levallois-perret', 1::smallint, '10:00'::time, '19:00'::time),
    ('saint-algue-levallois-levallois-perret', 2::smallint, '10:00'::time, '19:00'::time),
    ('saint-algue-levallois-levallois-perret', 3::smallint, '10:00'::time, '19:00'::time),
    ('saint-algue-levallois-levallois-perret', 4::smallint, '10:00'::time, '19:00'::time),
    ('saint-algue-levallois-levallois-perret', 5::smallint, '10:00'::time, '19:00'::time),
    ('saint-algue-levallois-levallois-perret', 6::smallint, '10:00'::time, '19:00'::time),
    ('atelier-w-coiffeur-institut-neuilly-sur-seine', 0::smallint, null, null),
    ('atelier-w-coiffeur-institut-neuilly-sur-seine', 1::smallint, null, null),
    ('atelier-w-coiffeur-institut-neuilly-sur-seine', 2::smallint, '10:00'::time, '18:30'::time),
    ('atelier-w-coiffeur-institut-neuilly-sur-seine', 3::smallint, '10:00'::time, '18:30'::time),
    ('atelier-w-coiffeur-institut-neuilly-sur-seine', 4::smallint, '10:00'::time, '18:30'::time),
    ('atelier-w-coiffeur-institut-neuilly-sur-seine', 5::smallint, '10:00'::time, '18:30'::time),
    ('atelier-w-coiffeur-institut-neuilly-sur-seine', 6::smallint, '10:00'::time, '18:30'::time),
    ('racine-beaute-nanterre', 0::smallint, '11:00'::time, '17:00'::time),
    ('racine-beaute-nanterre', 1::smallint, '11:00'::time, '18:00'::time),
    ('racine-beaute-nanterre', 2::smallint, '11:00'::time, '20:00'::time),
    ('racine-beaute-nanterre', 3::smallint, '10:00'::time, '19:00'::time),
    ('racine-beaute-nanterre', 4::smallint, '10:00'::time, '19:00'::time),
    ('racine-beaute-nanterre', 5::smallint, '10:00'::time, '21:00'::time),
    ('racine-beaute-nanterre', 6::smallint, '09:00'::time, '19:00'::time),
    ('lorentz-by-gerard-puteaux', 0::smallint, null, null),
    ('lorentz-by-gerard-puteaux', 1::smallint, null, null),
    ('lorentz-by-gerard-puteaux', 2::smallint, '10:00'::time, '19:00'::time),
    ('lorentz-by-gerard-puteaux', 3::smallint, '10:00'::time, '19:00'::time),
    ('lorentz-by-gerard-puteaux', 4::smallint, '10:30'::time, '20:30'::time),
    ('lorentz-by-gerard-puteaux', 5::smallint, '10:00'::time, '19:00'::time),
    ('lorentz-by-gerard-puteaux', 6::smallint, '09:30'::time, '19:00'::time),
    ('cyril-franck-montrouge', 0::smallint, null, null),
    ('cyril-franck-montrouge', 1::smallint, null, null),
    ('cyril-franck-montrouge', 2::smallint, '10:00'::time, '18:30'::time),
    ('cyril-franck-montrouge', 3::smallint, '10:00'::time, '18:30'::time),
    ('cyril-franck-montrouge', 4::smallint, '11:00'::time, '20:30'::time),
    ('cyril-franck-montrouge', 5::smallint, '10:00'::time, '18:30'::time),
    ('cyril-franck-montrouge', 6::smallint, '10:00'::time, '18:30'::time),
    ('adriano-tosca-rueil-malmaison', 0::smallint, null, null),
    ('adriano-tosca-rueil-malmaison', 1::smallint, null, null),
    ('adriano-tosca-rueil-malmaison', 2::smallint, '10:00'::time, '19:00'::time),
    ('adriano-tosca-rueil-malmaison', 3::smallint, '10:00'::time, '19:00'::time),
    ('adriano-tosca-rueil-malmaison', 4::smallint, '11:00'::time, '20:00'::time),
    ('adriano-tosca-rueil-malmaison', 5::smallint, '10:00'::time, '19:00'::time),
    ('adriano-tosca-rueil-malmaison', 6::smallint, '10:00'::time, '18:00'::time),
    ('jacques-dessange-saint-cloud-saint-cloud', 0::smallint, null, null),
    ('jacques-dessange-saint-cloud-saint-cloud', 1::smallint, null, null),
    ('jacques-dessange-saint-cloud-saint-cloud', 2::smallint, '09:30'::time, '18:30'::time),
    ('jacques-dessange-saint-cloud-saint-cloud', 3::smallint, '09:30'::time, '18:30'::time),
    ('jacques-dessange-saint-cloud-saint-cloud', 4::smallint, '09:30'::time, '18:30'::time),
    ('jacques-dessange-saint-cloud-saint-cloud', 5::smallint, '09:30'::time, '18:30'::time),
    ('jacques-dessange-saint-cloud-saint-cloud', 6::smallint, '09:30'::time, '18:30'::time),
    ('ramon-coiffures-diffusion-meudon', 0::smallint, null, null),
    ('ramon-coiffures-diffusion-meudon', 1::smallint, '09:00'::time, '19:00'::time),
    ('ramon-coiffures-diffusion-meudon', 2::smallint, '09:00'::time, '19:00'::time),
    ('ramon-coiffures-diffusion-meudon', 3::smallint, '09:00'::time, '19:00'::time),
    ('ramon-coiffures-diffusion-meudon', 4::smallint, '09:00'::time, '19:00'::time),
    ('ramon-coiffures-diffusion-meudon', 5::smallint, '09:00'::time, '19:00'::time),
    ('ramon-coiffures-diffusion-meudon', 6::smallint, '09:00'::time, '19:00'::time),
    ('melissa-coiffure-courbevoie', 0::smallint, null, null),
    ('melissa-coiffure-courbevoie', 1::smallint, null, null),
    ('melissa-coiffure-courbevoie', 2::smallint, '09:30'::time, '19:00'::time),
    ('melissa-coiffure-courbevoie', 3::smallint, '09:30'::time, '19:00'::time),
    ('melissa-coiffure-courbevoie', 4::smallint, '09:30'::time, '19:00'::time),
    ('melissa-coiffure-courbevoie', 5::smallint, '09:30'::time, '19:00'::time),
    ('melissa-coiffure-courbevoie', 6::smallint, '09:30'::time, '19:00'::time),
    ('robinson-coiffure-le-plessis-robinson', 0::smallint, null, null),
    ('robinson-coiffure-le-plessis-robinson', 1::smallint, null, null),
    ('robinson-coiffure-le-plessis-robinson', 2::smallint, '09:00'::time, '18:30'::time),
    ('robinson-coiffure-le-plessis-robinson', 3::smallint, '09:00'::time, '18:30'::time),
    ('robinson-coiffure-le-plessis-robinson', 4::smallint, '09:00'::time, '18:30'::time),
    ('robinson-coiffure-le-plessis-robinson', 5::smallint, '09:00'::time, '20:00'::time),
    ('robinson-coiffure-le-plessis-robinson', 6::smallint, '09:00'::time, '18:00'::time)
  ) as h(slug, jour, ouvre, ferme)
    on h.slug = s.slug
 where s.demo = false
   and s.gerant_id is null
on conflict (salon_id, jour) do update
  set ouvre = excluded.ouvre,
      ferme = excluded.ferme;

-- Ignorés (lot 3/5) :
-- la-casa-barbier-levallois-perret : pas d'horaires trouvés
-- salon-de-coiffure-edouard-medioni-issy-les-moulineaux : pas d'horaires trouvés
-- alex-coiffure-issy-les-moulineaux : pas d'horaires trouvés
-- caprices-des-dames-issy-les-moulineaux : coupure méridienne (9h-12h puis 14h-19h du mardi au vendredi)
-- ana-et-co-issy-les-moulineaux : pas d'horaires trouvés

insert into public.horaires (salon_id, jour, ouvre, ferme)
select s.id, h.jour, h.ouvre, h.ferme
  from public.salons s
  join (values
    ('atelier-dessaigne-boulogne-billancourt', 1::smallint, '10:00'::time, '19:00'::time),
    ('atelier-dessaigne-boulogne-billancourt', 2::smallint, '09:30'::time, '19:00'::time),
    ('atelier-dessaigne-boulogne-billancourt', 3::smallint, '09:30'::time, '19:00'::time),
    ('atelier-dessaigne-boulogne-billancourt', 4::smallint, '10:00'::time, '19:00'::time),
    ('atelier-dessaigne-boulogne-billancourt', 5::smallint, '09:30'::time, '18:30'::time),
    ('atelier-dessaigne-boulogne-billancourt', 6::smallint, '09:00'::time, '19:00'::time),
    ('atelier-dessaigne-boulogne-billancourt', 0::smallint, null, null),
    ('espace-coiffure-beaute-neuilly-sur-seine', 1::smallint, null, null),
    ('espace-coiffure-beaute-neuilly-sur-seine', 2::smallint, '09:30'::time, '19:00'::time),
    ('espace-coiffure-beaute-neuilly-sur-seine', 3::smallint, '09:30'::time, '19:00'::time),
    ('espace-coiffure-beaute-neuilly-sur-seine', 4::smallint, '09:30'::time, '20:00'::time),
    ('espace-coiffure-beaute-neuilly-sur-seine', 5::smallint, '09:30'::time, '19:00'::time),
    ('espace-coiffure-beaute-neuilly-sur-seine', 6::smallint, '09:30'::time, '18:00'::time),
    ('espace-coiffure-beaute-neuilly-sur-seine', 0::smallint, null, null),
    ('barberland-clamart-clamart', 1::smallint, null, null),
    ('barberland-clamart-clamart', 2::smallint, '10:00'::time, '19:30'::time),
    ('barberland-clamart-clamart', 3::smallint, '10:00'::time, '19:30'::time),
    ('barberland-clamart-clamart', 4::smallint, '10:00'::time, '19:30'::time),
    ('barberland-clamart-clamart', 5::smallint, '09:30'::time, '20:00'::time),
    ('barberland-clamart-clamart', 6::smallint, '09:30'::time, '20:00'::time),
    ('barberland-clamart-clamart', 0::smallint, '10:00'::time, '20:00'::time),
    ('eric-stipa-bois-colombes', 1::smallint, null, null),
    ('eric-stipa-bois-colombes', 2::smallint, '10:00'::time, '19:00'::time),
    ('eric-stipa-bois-colombes', 3::smallint, '10:00'::time, '19:00'::time),
    ('eric-stipa-bois-colombes', 4::smallint, '10:00'::time, '19:00'::time),
    ('eric-stipa-bois-colombes', 5::smallint, '10:00'::time, '19:00'::time),
    ('eric-stipa-bois-colombes', 6::smallint, '09:00'::time, '19:00'::time),
    ('eric-stipa-bois-colombes', 0::smallint, null, null),
    ('l-artisan-coiffeur-bourg-la-reine', 1::smallint, '09:00'::time, '19:00'::time),
    ('l-artisan-coiffeur-bourg-la-reine', 2::smallint, '08:30'::time, '19:00'::time),
    ('l-artisan-coiffeur-bourg-la-reine', 3::smallint, '08:30'::time, '19:00'::time),
    ('l-artisan-coiffeur-bourg-la-reine', 4::smallint, '08:30'::time, '19:00'::time),
    ('l-artisan-coiffeur-bourg-la-reine', 5::smallint, '08:30'::time, '19:00'::time),
    ('l-artisan-coiffeur-bourg-la-reine', 6::smallint, '08:30'::time, '19:00'::time),
    ('l-artisan-coiffeur-bourg-la-reine', 0::smallint, null, null),
    ('her-look-sceaux', 1::smallint, '09:30'::time, '18:00'::time),
    ('her-look-sceaux', 2::smallint, '09:30'::time, '18:00'::time),
    ('her-look-sceaux', 3::smallint, '09:30'::time, '18:00'::time),
    ('her-look-sceaux', 4::smallint, '09:30'::time, '18:00'::time),
    ('her-look-sceaux', 5::smallint, '09:30'::time, '18:00'::time),
    ('her-look-sceaux', 6::smallint, '09:30'::time, '18:00'::time),
    ('her-look-sceaux', 0::smallint, null, null),
    ('barber-shop-by-bou-bagneux-bagneux', 1::smallint, null, null),
    ('barber-shop-by-bou-bagneux-bagneux', 2::smallint, '10:00'::time, '19:00'::time),
    ('barber-shop-by-bou-bagneux-bagneux', 3::smallint, '10:00'::time, '19:00'::time),
    ('barber-shop-by-bou-bagneux-bagneux', 4::smallint, '10:00'::time, '19:00'::time),
    ('barber-shop-by-bou-bagneux-bagneux', 5::smallint, '10:00'::time, '19:00'::time),
    ('barber-shop-by-bou-bagneux-bagneux', 6::smallint, '10:00'::time, '19:00'::time),
    ('barber-shop-by-bou-bagneux-bagneux', 0::smallint, '10:00'::time, '19:00'::time),
    ('gentlemen-s-barber-shop-bagneux', 1::smallint, '09:30'::time, '20:30'::time),
    ('gentlemen-s-barber-shop-bagneux', 2::smallint, '09:30'::time, '20:30'::time),
    ('gentlemen-s-barber-shop-bagneux', 3::smallint, '09:30'::time, '20:30'::time),
    ('gentlemen-s-barber-shop-bagneux', 4::smallint, '09:30'::time, '20:30'::time),
    ('gentlemen-s-barber-shop-bagneux', 5::smallint, '09:30'::time, '20:30'::time),
    ('gentlemen-s-barber-shop-bagneux', 6::smallint, '09:30'::time, '20:30'::time),
    ('gentlemen-s-barber-shop-bagneux', 0::smallint, '09:30'::time, '20:30'::time),
    ('hair-cut-montrouge-montrouge', 1::smallint, null, null),
    ('hair-cut-montrouge-montrouge', 2::smallint, '09:30'::time, '19:00'::time),
    ('hair-cut-montrouge-montrouge', 3::smallint, '09:30'::time, '19:00'::time),
    ('hair-cut-montrouge-montrouge', 4::smallint, '10:00'::time, '20:00'::time),
    ('hair-cut-montrouge-montrouge', 5::smallint, '09:30'::time, '19:00'::time),
    ('hair-cut-montrouge-montrouge', 6::smallint, '09:00'::time, '18:00'::time),
    ('hair-cut-montrouge-montrouge', 0::smallint, null, null),
    ('so-beauty-hair-malakoff', 1::smallint, null, null),
    ('so-beauty-hair-malakoff', 2::smallint, '10:00'::time, '19:00'::time),
    ('so-beauty-hair-malakoff', 3::smallint, '10:00'::time, '19:00'::time),
    ('so-beauty-hair-malakoff', 4::smallint, '10:00'::time, '19:00'::time),
    ('so-beauty-hair-malakoff', 5::smallint, '10:00'::time, '19:00'::time),
    ('so-beauty-hair-malakoff', 6::smallint, '10:00'::time, '19:00'::time),
    ('so-beauty-hair-malakoff', 0::smallint, null, null),
    ('oshun-by-dicaro-montrouge', 1::smallint, null, null),
    ('oshun-by-dicaro-montrouge', 2::smallint, '10:00'::time, '19:00'::time),
    ('oshun-by-dicaro-montrouge', 3::smallint, '10:00'::time, '19:00'::time),
    ('oshun-by-dicaro-montrouge', 4::smallint, '10:00'::time, '19:00'::time),
    ('oshun-by-dicaro-montrouge', 5::smallint, '10:00'::time, '19:00'::time),
    ('oshun-by-dicaro-montrouge', 6::smallint, '10:00'::time, '19:00'::time),
    ('oshun-by-dicaro-montrouge', 0::smallint, null, null),
    ('aukeo-creation-bourg-la-reine', 1::smallint, '11:00'::time, '17:00'::time),
    ('aukeo-creation-bourg-la-reine', 2::smallint, '09:00'::time, '19:00'::time),
    ('aukeo-creation-bourg-la-reine', 3::smallint, '09:00'::time, '19:00'::time),
    ('aukeo-creation-bourg-la-reine', 4::smallint, '09:00'::time, '19:00'::time),
    ('aukeo-creation-bourg-la-reine', 5::smallint, '09:00'::time, '19:00'::time),
    ('aukeo-creation-bourg-la-reine', 6::smallint, '09:00'::time, '19:00'::time),
    ('aukeo-creation-bourg-la-reine', 0::smallint, '11:00'::time, '17:00'::time),
    ('franck-provost-la-garenne-colombes-la-garenne-colombes', 1::smallint, '10:00'::time, '19:00'::time),
    ('franck-provost-la-garenne-colombes-la-garenne-colombes', 2::smallint, '10:00'::time, '19:00'::time),
    ('franck-provost-la-garenne-colombes-la-garenne-colombes', 3::smallint, '10:00'::time, '19:00'::time),
    ('franck-provost-la-garenne-colombes-la-garenne-colombes', 4::smallint, '10:00'::time, '19:00'::time),
    ('franck-provost-la-garenne-colombes-la-garenne-colombes', 5::smallint, '10:00'::time, '19:00'::time),
    ('franck-provost-la-garenne-colombes-la-garenne-colombes', 6::smallint, '10:00'::time, '19:00'::time),
    ('franck-provost-la-garenne-colombes-la-garenne-colombes', 0::smallint, null, null),
    ('l-atelier-b-la-garenne-colombes', 1::smallint, null, null),
    ('l-atelier-b-la-garenne-colombes', 2::smallint, '10:00'::time, '19:00'::time),
    ('l-atelier-b-la-garenne-colombes', 3::smallint, '10:00'::time, '19:00'::time),
    ('l-atelier-b-la-garenne-colombes', 4::smallint, '10:00'::time, '19:00'::time),
    ('l-atelier-b-la-garenne-colombes', 5::smallint, '10:00'::time, '20:00'::time),
    ('l-atelier-b-la-garenne-colombes', 6::smallint, '09:00'::time, '19:00'::time),
    ('l-atelier-b-la-garenne-colombes', 0::smallint, null, null),
    ('un-moment-pour-soi-colombes', 1::smallint, null, null),
    ('un-moment-pour-soi-colombes', 2::smallint, '09:30'::time, '19:00'::time),
    ('un-moment-pour-soi-colombes', 3::smallint, '09:30'::time, '19:00'::time),
    ('un-moment-pour-soi-colombes', 4::smallint, '09:30'::time, '21:00'::time),
    ('un-moment-pour-soi-colombes', 5::smallint, '09:30'::time, '19:00'::time),
    ('un-moment-pour-soi-colombes', 6::smallint, '10:00'::time, '19:00'::time),
    ('un-moment-pour-soi-colombes', 0::smallint, null, null),
    ('jean-francois-michelle-fontenay-aux-roses', 1::smallint, null, null),
    ('jean-francois-michelle-fontenay-aux-roses', 2::smallint, '09:30'::time, '19:00'::time),
    ('jean-francois-michelle-fontenay-aux-roses', 3::smallint, '09:30'::time, '19:00'::time),
    ('jean-francois-michelle-fontenay-aux-roses', 4::smallint, '09:30'::time, '19:30'::time),
    ('jean-francois-michelle-fontenay-aux-roses', 5::smallint, '09:00'::time, '19:00'::time),
    ('jean-francois-michelle-fontenay-aux-roses', 6::smallint, '09:00'::time, '18:00'::time),
    ('jean-francois-michelle-fontenay-aux-roses', 0::smallint, null, null),
    ('lydia-coiffure-fontenay-aux-roses', 1::smallint, null, null),
    ('lydia-coiffure-fontenay-aux-roses', 2::smallint, '09:30'::time, '19:00'::time),
    ('lydia-coiffure-fontenay-aux-roses', 3::smallint, '09:30'::time, '19:00'::time),
    ('lydia-coiffure-fontenay-aux-roses', 4::smallint, '10:00'::time, '20:00'::time),
    ('lydia-coiffure-fontenay-aux-roses', 5::smallint, '09:30'::time, '19:00'::time),
    ('lydia-coiffure-fontenay-aux-roses', 6::smallint, '09:00'::time, '18:30'::time),
    ('lydia-coiffure-fontenay-aux-roses', 0::smallint, null, null)
  ) as h(slug, jour, ouvre, ferme)
    on h.slug = s.slug
 where s.demo = false
   and s.gerant_id is null
on conflict (salon_id, jour) do update
  set ouvre = excluded.ouvre,
      ferme = excluded.ferme;

-- Ignorés (lot 4/5) :
-- a-beauty-r-rueil-malmaison : pas d'horaires trouvés
-- rosique-christine-chatenay-malabry : pas d'horaires trouvés
-- attitude-coiffure-boulogne-billancourt : sources contradictoires, pas de détail par jour vérifiable
-- corinne-brault-la-garenne-colombes : horaires incomplets, pas de grille complète
-- h-barber-la-garenne-colombes : pas d'horaires trouvés
-- un-look-pour-tous-la-garenne-la-garenne-colombes : horaires incomplets, pas de confirmation croisée
-- coiffure-sampaio-fontenay-aux-roses : salon introuvable dans les recherches

insert into public.horaires (salon_id, jour, ouvre, ferme)
select s.id, h.jour, h.ouvre, h.ferme
  from public.salons s
  join (values
    ('j-s-coiffure-chaville', 0::smallint, null, null),
    ('j-s-coiffure-chaville', 1::smallint, '09:00'::time, '18:30'::time),
    ('j-s-coiffure-chaville', 2::smallint, '09:00'::time, '18:30'::time),
    ('j-s-coiffure-chaville', 3::smallint, null, null),
    ('j-s-coiffure-chaville', 4::smallint, '09:00'::time, '18:30'::time),
    ('j-s-coiffure-chaville', 5::smallint, '09:00'::time, '18:30'::time),
    ('j-s-coiffure-chaville', 6::smallint, '09:00'::time, '18:00'::time),
    ('nature-coiff-meudon', 0::smallint, null, null),
    ('nature-coiff-meudon', 1::smallint, null, null),
    ('nature-coiff-meudon', 2::smallint, '09:00'::time, '18:00'::time),
    ('nature-coiff-meudon', 3::smallint, '09:00'::time, '18:00'::time),
    ('nature-coiff-meudon', 4::smallint, '09:00'::time, '18:00'::time),
    ('nature-coiff-meudon', 5::smallint, '09:00'::time, '18:00'::time),
    ('nature-coiff-meudon', 6::smallint, '09:00'::time, '18:00'::time),
    ('the-platinum-barber-vlg-villeneuve-la-garenne', 0::smallint, '10:00'::time, '20:00'::time),
    ('the-platinum-barber-vlg-villeneuve-la-garenne', 1::smallint, '10:00'::time, '20:00'::time),
    ('the-platinum-barber-vlg-villeneuve-la-garenne', 2::smallint, '10:00'::time, '20:00'::time),
    ('the-platinum-barber-vlg-villeneuve-la-garenne', 3::smallint, '10:00'::time, '20:00'::time),
    ('the-platinum-barber-vlg-villeneuve-la-garenne', 4::smallint, '10:00'::time, '20:00'::time),
    ('the-platinum-barber-vlg-villeneuve-la-garenne', 5::smallint, '10:00'::time, '20:00'::time),
    ('the-platinum-barber-vlg-villeneuve-la-garenne', 6::smallint, '10:00'::time, '20:00'::time),
    ('barberland-ii-sevres', 0::smallint, '10:00'::time, '18:30'::time),
    ('barberland-ii-sevres', 1::smallint, '09:30'::time, '19:30'::time),
    ('barberland-ii-sevres', 2::smallint, '09:30'::time, '19:30'::time),
    ('barberland-ii-sevres', 3::smallint, '09:30'::time, '19:30'::time),
    ('barberland-ii-sevres', 4::smallint, '09:30'::time, '19:30'::time),
    ('barberland-ii-sevres', 5::smallint, '09:30'::time, '19:30'::time),
    ('barberland-ii-sevres', 6::smallint, '09:30'::time, '19:30'::time),
    ('barbershop-longchamp-suresnes', 0::smallint, '09:30'::time, '17:45'::time),
    ('barbershop-longchamp-suresnes', 1::smallint, '09:30'::time, '17:45'::time),
    ('barbershop-longchamp-suresnes', 2::smallint, '09:30'::time, '17:45'::time),
    ('barbershop-longchamp-suresnes', 3::smallint, '09:30'::time, '17:45'::time),
    ('barbershop-longchamp-suresnes', 4::smallint, '09:30'::time, '17:45'::time),
    ('barbershop-longchamp-suresnes', 5::smallint, '09:30'::time, '17:45'::time),
    ('barbershop-longchamp-suresnes', 6::smallint, '09:30'::time, '17:45'::time),
    ('barberzer-bagneux', 0::smallint, null, null),
    ('barberzer-bagneux', 1::smallint, null, null),
    ('barberzer-bagneux', 2::smallint, '10:00'::time, '20:00'::time),
    ('barberzer-bagneux', 3::smallint, '10:00'::time, '20:00'::time),
    ('barberzer-bagneux', 4::smallint, '10:00'::time, '20:00'::time),
    ('barberzer-bagneux', 5::smallint, '10:00'::time, '20:00'::time),
    ('barberzer-bagneux', 6::smallint, '10:00'::time, '20:00'::time),
    ('the-barber-92-asnieres-sur-seine', 0::smallint, '10:00'::time, '20:30'::time),
    ('the-barber-92-asnieres-sur-seine', 1::smallint, '10:00'::time, '20:30'::time),
    ('the-barber-92-asnieres-sur-seine', 2::smallint, '10:00'::time, '20:30'::time),
    ('the-barber-92-asnieres-sur-seine', 3::smallint, '10:00'::time, '20:30'::time),
    ('the-barber-92-asnieres-sur-seine', 4::smallint, '10:00'::time, '20:30'::time),
    ('the-barber-92-asnieres-sur-seine', 5::smallint, '10:00'::time, '20:30'::time),
    ('the-barber-92-asnieres-sur-seine', 6::smallint, '10:00'::time, '20:30'::time),
    ('mjm-coiffure-suresnes', 0::smallint, null, null),
    ('mjm-coiffure-suresnes', 1::smallint, null, null),
    ('mjm-coiffure-suresnes', 2::smallint, '10:00'::time, '19:00'::time),
    ('mjm-coiffure-suresnes', 3::smallint, '10:00'::time, '19:00'::time),
    ('mjm-coiffure-suresnes', 4::smallint, '10:00'::time, '19:00'::time),
    ('mjm-coiffure-suresnes', 5::smallint, '10:00'::time, '19:00'::time),
    ('mjm-coiffure-suresnes', 6::smallint, '09:30'::time, '19:00'::time),
    ('look-92-villeneuve-la-garenne', 0::smallint, null, null),
    ('look-92-villeneuve-la-garenne', 1::smallint, null, null),
    ('look-92-villeneuve-la-garenne', 2::smallint, '09:00'::time, '19:00'::time),
    ('look-92-villeneuve-la-garenne', 3::smallint, '09:00'::time, '19:00'::time),
    ('look-92-villeneuve-la-garenne', 4::smallint, '09:00'::time, '19:00'::time),
    ('look-92-villeneuve-la-garenne', 5::smallint, '09:00'::time, '19:00'::time),
    ('look-92-villeneuve-la-garenne', 6::smallint, '09:00'::time, '18:00'::time),
    ('dk-hair-gennevilliers', 0::smallint, null, null),
    ('dk-hair-gennevilliers', 1::smallint, '10:00'::time, '19:00'::time),
    ('dk-hair-gennevilliers', 2::smallint, '10:00'::time, '19:00'::time),
    ('dk-hair-gennevilliers', 3::smallint, '10:00'::time, '19:00'::time),
    ('dk-hair-gennevilliers', 4::smallint, '10:00'::time, '19:00'::time),
    ('dk-hair-gennevilliers', 5::smallint, '10:00'::time, '19:00'::time),
    ('dk-hair-gennevilliers', 6::smallint, '10:00'::time, '19:00'::time),
    ('dop-coiffure-clichy', 0::smallint, '09:30'::time, '20:00'::time),
    ('dop-coiffure-clichy', 1::smallint, '09:30'::time, '20:00'::time),
    ('dop-coiffure-clichy', 2::smallint, '09:30'::time, '20:00'::time),
    ('dop-coiffure-clichy', 3::smallint, '09:30'::time, '20:00'::time),
    ('dop-coiffure-clichy', 4::smallint, '09:30'::time, '20:00'::time),
    ('dop-coiffure-clichy', 5::smallint, '09:30'::time, '20:00'::time),
    ('dop-coiffure-clichy', 6::smallint, '09:30'::time, '20:00'::time),
    ('shea-hair-colombes', 0::smallint, null, null),
    ('shea-hair-colombes', 1::smallint, null, null),
    ('shea-hair-colombes', 2::smallint, '10:00'::time, '19:00'::time),
    ('shea-hair-colombes', 3::smallint, '10:00'::time, '19:00'::time),
    ('shea-hair-colombes', 4::smallint, '10:00'::time, '19:00'::time),
    ('shea-hair-colombes', 5::smallint, '10:00'::time, '19:00'::time),
    ('shea-hair-colombes', 6::smallint, '10:00'::time, '20:00'::time),
    ('la-moustache-du-gentleman-levallois-perret', 0::smallint, null, null),
    ('la-moustache-du-gentleman-levallois-perret', 1::smallint, '10:00'::time, '19:30'::time),
    ('la-moustache-du-gentleman-levallois-perret', 2::smallint, '10:00'::time, '19:30'::time),
    ('la-moustache-du-gentleman-levallois-perret', 3::smallint, '10:00'::time, '19:30'::time),
    ('la-moustache-du-gentleman-levallois-perret', 4::smallint, '10:00'::time, '19:30'::time),
    ('la-moustache-du-gentleman-levallois-perret', 5::smallint, '10:00'::time, '19:30'::time),
    ('la-moustache-du-gentleman-levallois-perret', 6::smallint, '10:00'::time, '20:00'::time),
    ('les-barboristes-levallois-levallois-perret', 0::smallint, null, null),
    ('les-barboristes-levallois-levallois-perret', 1::smallint, null, null),
    ('les-barboristes-levallois-levallois-perret', 2::smallint, '10:30'::time, '20:00'::time),
    ('les-barboristes-levallois-levallois-perret', 3::smallint, '10:30'::time, '20:00'::time),
    ('les-barboristes-levallois-levallois-perret', 4::smallint, '10:30'::time, '20:00'::time),
    ('les-barboristes-levallois-levallois-perret', 5::smallint, '10:30'::time, '20:00'::time),
    ('les-barboristes-levallois-levallois-perret', 6::smallint, '09:00'::time, '19:00'::time),
    ('les-belles-barbes-issy-les-moulineaux', 0::smallint, null, null),
    ('les-belles-barbes-issy-les-moulineaux', 1::smallint, '10:00'::time, '19:00'::time),
    ('les-belles-barbes-issy-les-moulineaux', 2::smallint, '10:00'::time, '19:00'::time),
    ('les-belles-barbes-issy-les-moulineaux', 3::smallint, '10:00'::time, '19:00'::time),
    ('les-belles-barbes-issy-les-moulineaux', 4::smallint, '10:00'::time, '19:00'::time),
    ('les-belles-barbes-issy-les-moulineaux', 5::smallint, '10:00'::time, '19:00'::time),
    ('les-belles-barbes-issy-les-moulineaux', 6::smallint, '09:00'::time, '19:00'::time),
    ('kutbro-barber-shop-rueil-malmaison', 0::smallint, '10:00'::time, '20:00'::time),
    ('kutbro-barber-shop-rueil-malmaison', 1::smallint, null, null),
    ('kutbro-barber-shop-rueil-malmaison', 2::smallint, '10:00'::time, '20:00'::time),
    ('kutbro-barber-shop-rueil-malmaison', 3::smallint, '10:00'::time, '20:00'::time),
    ('kutbro-barber-shop-rueil-malmaison', 4::smallint, '10:00'::time, '20:00'::time),
    ('kutbro-barber-shop-rueil-malmaison', 5::smallint, '10:00'::time, '20:00'::time),
    ('kutbro-barber-shop-rueil-malmaison', 6::smallint, '10:00'::time, '20:00'::time),
    ('the-wood-barber-rueil-malmaison', 0::smallint, '10:00'::time, '14:00'::time),
    ('the-wood-barber-rueil-malmaison', 1::smallint, '10:00'::time, '20:00'::time),
    ('the-wood-barber-rueil-malmaison', 2::smallint, '10:00'::time, '20:00'::time),
    ('the-wood-barber-rueil-malmaison', 3::smallint, '10:00'::time, '20:00'::time),
    ('the-wood-barber-rueil-malmaison', 4::smallint, '10:00'::time, '20:00'::time),
    ('the-wood-barber-rueil-malmaison', 5::smallint, '10:00'::time, '20:00'::time),
    ('the-wood-barber-rueil-malmaison', 6::smallint, '10:00'::time, '20:00'::time),
    ('joe-s-barbershop-clichy', 0::smallint, '11:00'::time, '19:00'::time),
    ('joe-s-barbershop-clichy', 1::smallint, '10:00'::time, '20:00'::time),
    ('joe-s-barbershop-clichy', 2::smallint, '10:00'::time, '20:00'::time),
    ('joe-s-barbershop-clichy', 3::smallint, '10:00'::time, '20:00'::time),
    ('joe-s-barbershop-clichy', 4::smallint, '10:00'::time, '20:00'::time),
    ('joe-s-barbershop-clichy', 5::smallint, '10:00'::time, '20:00'::time),
    ('joe-s-barbershop-clichy', 6::smallint, '10:00'::time, '20:00'::time)
  ) as h(slug, jour, ouvre, ferme)
    on h.slug = s.slug
 where s.demo = false
   and s.gerant_id is null
on conflict (salon_id, jour) do update
  set ouvre = excluded.ouvre,
      ferme = excluded.ferme;

-- Ignorés (lot 5/5) :
-- salon-lph-chaville : horaires complets introuvables
-- bcb-barber-garches : horaires en semaine indisponibles
-- the-barbers-city-bagneux : sources contradictoires entre agrégateurs
-- barber-shop-les-amis-bois-colombes : coupure méridienne le vendredi
-- beauty-glam-villeneuve-la-garenne : seule une plage globale trouvée, sans détail par jour
-- beaulieu-coiffure-bourg-la-reine : pas d'horaires trouvés
-- coiffure-de-l-amitie-montrouge : semble avoir fermé fin 2023, à vérifier séparément

-- Contrôle : combien de salons ont désormais des horaires (pilote 0006
-- + ce lot), et combien de lignes ça représente au total.
select
  count(distinct h.salon_id) as "salons reels avec horaires",
  count(*)                   as "lignes horaires"
  from public.horaires h
  join public.salons s on s.id = h.salon_id
 where s.demo = false;
